import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase-server'

export async function GET(
  _request: NextRequest,
  { params }: { params: { reportId: string } }
) {
  const supabase = await createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: workspace } = await supabase
    .from('workspaces')
    .select('id, name')
    .eq('owner_id', user.id)
    .single()

  if (!workspace) return NextResponse.json({ error: 'No workspace' }, { status: 404 })

  const { data: report } = await supabase
    .from('reports')
    .select('*')
    .eq('id', params.reportId)
    .eq('workspace_id', workspace.id)
    .single()

  if (!report) return NextResponse.json({ error: 'Report not found' }, { status: 404 })

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Rival Intelligence Report — ${report.period_end}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #09090b;
      color: #fafafa;
      padding: 48px;
      max-width: 800px;
      margin: 0 auto;
    }
    @media print {
      body { padding: 32px; background: #fff; color: #111; }
      .no-print { display: none; }
    }
    .header { margin-bottom: 40px; padding-bottom: 24px; border-bottom: 1px solid #27272a; }
    .logo { font-size: 22px; font-weight: 700; color: #10b981; letter-spacing: -0.5px; margin-bottom: 8px; }
    .meta { font-size: 13px; color: #71717a; }
    .stats { display: flex; gap: 40px; margin: 32px 0; padding: 24px; background: #111113; border: 1px solid #27272a; border-radius: 12px; }
    .stat-label { font-size: 12px; color: #52525b; margin-bottom: 4px; }
    .stat-value { font-size: 28px; font-weight: 700; color: #fff; }
    .report-content { margin-top: 32px; line-height: 1.7; }
    .print-btn {
      display: inline-flex; align-items: center; gap: 8px;
      margin-bottom: 32px; padding: 10px 20px; border-radius: 8px;
      background: #10b981; color: #000; font-size: 14px; font-weight: 600;
      border: none; cursor: pointer;
    }
    .footer { margin-top: 48px; padding-top: 20px; border-top: 1px solid #27272a; font-size: 12px; color: #3f3f46; }
  </style>
</head>
<body>
  <div class="no-print" style="margin-bottom:24px;">
    <button class="print-btn" onclick="window.print()">⬇ Download as PDF</button>
    <span style="font-size:13px;color:#52525b;margin-left:12px;">Use your browser's Print dialog → Save as PDF</span>
  </div>

  <div class="header">
    <div class="logo">Rival</div>
    <div class="meta">Intelligence Report · ${workspace.name} · Week ending ${report.period_end}</div>
  </div>

  <div class="stats">
    <div>
      <div class="stat-label">Competitors monitored</div>
      <div class="stat-value" style="color:#fff">${report.changes_count !== undefined ? '—' : '—'}</div>
    </div>
    <div>
      <div class="stat-label">Changes detected</div>
      <div class="stat-value" style="color:${report.changes_count > 0 ? '#10b981' : '#fff'}">${report.changes_count}</div>
    </div>
    <div>
      <div class="stat-label">Period</div>
      <div class="stat-value" style="font-size:16px;margin-top:8px;">${report.period_start} → ${report.period_end}</div>
    </div>
  </div>

  <div class="report-content">
    ${report.html_content}
  </div>

  <div class="footer">
    Generated by Rival · ${new Date().toLocaleDateString('en-GB')} · rival.io
  </div>
</body>
</html>`

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'private, no-cache',
    },
  })
}
